import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { randomBytes, pbkdf2Sync } from "node:crypto";
import { Miniflare } from "miniflare";
import worker, { beijingDate, beijingTime, imageMime, runReminders } from "../worker/index.ts";

test("任务、图片、权限、历史记录和微信提醒完整流程", async () => {
  const mf = new Miniflare({ modules:true, script:"export default {fetch(){return new Response('test')}}", compatibilityDate:"2026-06-22", d1Databases:{DB:"workflow-test"}, r2Buckets:["ASSETS_BUCKET"] });
  const originalFetch = globalThis.fetch;
  try {
    const DB = await mf.getD1Database("DB");
    for(const file of ["0001_initial.sql","0002_r2_assets.sql","0005_daily_tasks.sql","0006_pushplus_receipts.sql"]) {
      const sql = readFileSync(new URL(`../migrations/${file}`,import.meta.url),"utf8").replace(/--[^\n]*/g,"");
      for(const statement of sql.split(";").map(value=>value.trim()).filter(Boolean)) await DB.prepare(statement).run();
    }
    const env = {DB, ASSETS_BUCKET:await mf.getR2Bucket("ASSETS_BUCKET"), ADMIN_EMAIL:"admin@example.test", PUSHPLUS_TOKEN:"test-token", PUSHPLUS_SECRET_KEY:"test-secret", PUSHPLUS_CALLBACK_SECRET:"a".repeat(64)};
    const salt=randomBytes(16); const password="test-password";
    const hash=`10000:${salt.toString("hex")}:${pbkdf2Sync(password,salt,10000,32,"sha256").toString("hex")}`;
    await DB.prepare("INSERT INTO users(id,email,password_hash,display_name) VALUES('admin','admin@example.test',?1,'管理员')").bind(hash).run();
    const request=async(path,{method="GET",body,cookie,origin,raw}={})=>{
      const headers=new Headers();
      if(cookie)headers.set("Cookie",cookie);
      if(origin)headers.set("Origin",origin);
      if(body){headers.set("Content-Type","application/json");}
      return worker.fetch(new Request(`https://app.example.test${path}`,{method,headers,body:raw || (body?JSON.stringify(body):undefined)}),env);
    };
    const login=await request("/api/auth/login",{method:"POST",body:{email:env.ADMIN_EMAIL,password}});
    assert.equal(login.status,200);
    const admin=login.headers.get("set-cookie").split(";")[0];
    assert.equal((await (await request("/api/me",{cookie:admin})).json()).user.role,"admin");
    assert.equal((await request("/api/admin/tasks")).status,401);
    assert.equal((await request("/api/auth/register",{method:"POST",body:{email:env.ADMIN_EMAIL,password,displayName:"入侵者"}})).status,403);
    const register=await request("/api/auth/register",{method:"POST",body:{email:"member@example.test",password,displayName:"测试成员"}});
    assert.equal(register.status,201);
    const member=register.headers.get("set-cookie").split(";")[0];
    const memberUser=(await (await request("/api/me",{cookie:member})).json()).user;
    assert.equal(memberUser.role,"member");
    assert.equal((await request("/api/admin/tasks",{cookie:member})).status,403);
    assert.equal((await request("/api/admin/tasks",{cookie:admin,method:"POST",origin:"https://evil.example",body:{}})).status,403);
    const create=async(title,imagePolicy,days=[0,1,2,3,4,5,6])=>request("/api/admin/tasks",{cookie:admin,method:"POST",body:{title,description:"完成标准",weekdays:days,imagePolicy,active:true}});
    assert.equal((await create("无图任务","none")).status,201);
    assert.equal((await create("必传图片","required")).status,201);
    assert.equal((await create("选填图片","optional")).status,201);
    assert.equal((await create("无效任务","none",[])).status,400);
    const date=beijingDate();
    let today=await (await request("/api/today",{cookie:member})).json();
    assert.equal(today.tasks.length,3);
    const plain=today.tasks.find(task=>task.imagePolicy==="none");
    const required=today.tasks.find(task=>task.imagePolicy==="required");
    const optional=today.tasks.find(task=>task.imagePolicy==="optional");
    const finish=(task,imageIds=[],expectedDate=date)=>request(`/api/tasks/${task.id}/checkin`,{cookie:member,method:"POST",body:{date:expectedDate,imageIds}});
    assert.equal((await finish(required)).status,400);
    assert.equal((await finish(plain,[],"2020-01-01")).status,409);
    assert.equal((await finish(plain)).status,201);
    assert.equal((await finish(plain)).status,409);
    assert.equal((await finish(optional,["fake-id"])).status,400);
    assert.equal((await finish(optional,["a","b","c","d"])).status,400);
    const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==","base64");
    assert.equal(imageMime(png),"image/png");
    assert.equal(imageMime(new Uint8Array([1,2,3])),null);
    const form=new FormData();form.append("file",new File([png],"proof.png",{type:"image/png"}));
    const upload=await request("/api/assets/upload",{cookie:member,method:"POST",raw:form});
    assert.equal(upload.status,201);
    const image=(await upload.json()).asset;
    assert.equal((await request(image.url,{cookie:member})).status,200);
    assert.equal((await request(image.url,{cookie:admin})).status,200);
    const other=await request("/api/auth/register",{method:"POST",body:{email:"other@example.test",password,displayName:"其他成员"}});
    const otherCookie=other.headers.get("set-cookie").split(";")[0];
    assert.equal((await request(image.url,{cookie:otherCookie})).status,404);
    assert.equal((await request(`/api/tasks/${required.id}/checkin`,{cookie:otherCookie,method:"POST",body:{date,imageIds:[image.id]}})).status,400);
    assert.equal((await finish(required,[image.id])).status,201);
    today=await (await request("/api/today",{cookie:member})).json();
    assert.equal(today.tasks.find(task=>task.id===required.id).images[0].url,image.url);
    const overview=await (await request(`/api/admin/overview?date=${date}`,{cookie:admin})).json();
    assert.equal(overview.members.find(user=>user.id===memberUser.id).tasks.filter(task=>task.checkinId).length,2);
    assert.equal(overview.members.find(user=>user.id===memberUser.id).tasks.find(task=>task.id===required.id).images.length,1);
    const history=await (await request(`/api/records?month=${date.slice(0,7)}`,{cookie:member})).json();
    assert.equal(history.totalDays,1);
    assert.equal(history.days.find(day=>day.date===date).planned,3);
    assert.equal(history.days.find(day=>day.date===date).completed,2);
    await request(`/api/admin/tasks/${plain.id}`,{cookie:admin,method:"PUT",body:{title:"明天的新名称",description:"",weekdays:[0,1,2,3,4,5,6],imagePolicy:"required",active:false}});
    today=await (await request("/api/today",{cookie:member})).json();
    assert.equal(today.tasks.find(task=>task.id===plain.id).title,"无图任务");
    assert.equal(today.tasks.length,3);
    assert.equal((await request(`/api/tasks/${plain.id}/checkin`,{cookie:member,method:"DELETE",body:{date:"2020-01-01"}})).status,409);
    assert.equal((await request(`/api/tasks/${plain.id}/checkin`,{cookie:member,method:"DELETE",body:{date}})).status,200);
    const fakeForm=new FormData();fakeForm.append("file",new File(["not a png"],"fake.png",{type:"image/png"}));
    assert.equal((await request("/api/assets/upload",{cookie:member,method:"POST",raw:fakeForm})).status,400);
    assert.equal((await request("/api/records?month=2026-99",{cookie:member})).status,400);
    assert.equal(beijingDate(new Date("2026-10-09T16:01:00Z")),"2026-10-10");
    assert.equal(beijingTime(new Date("2026-10-09T16:01:00Z")),"00:01");
    assert.equal((await request("/api/notifications",{cookie:member,method:"PUT",body:{enabled:true}})).status,400);
    const code="b".repeat(64);
    await DB.prepare("INSERT INTO notification_preferences(user_id,binding_code,binding_expires_at) VALUES(?1,?2,datetime('now','+10 minutes'))").bind(memberUser.id,code).run();
    const callbackPath=`/api/pushplus/callback/${env.PUSHPLUS_CALLBACK_SECRET}`;
    assert.equal((await request("/api/pushplus/callback/"+"c".repeat(64),{method:"POST",body:{event:"add_friend"}})).status,403);
    const binding={event:"add_friend",qrCode:code,friendInfo:{token:"d".repeat(32),isFollow:1}};
    assert.equal((await request(callbackPath,{method:"POST",body:binding})).status,200);
    let notifications=await (await request("/api/notifications",{cookie:member})).json();
    assert.equal(notifications.bound,true);assert.equal(notifications.enabled,true);assert.equal("friendToken" in notifications,false);
    assert.equal((await request("/api/admin/reminders",{cookie:admin,method:"PUT",body:{enabled:true,reminderTime:"00:00",siteUrl:"http://insecure.test"}})).status,400);
    assert.equal((await request("/api/admin/reminders",{cookie:admin,method:"PUT",body:{enabled:true,reminderTime:"00:00",siteUrl:"https://app.example.test"}})).status,200);
    let sendCount=0;
    globalThis.fetch=async(url,init)=>{
      assert.equal(url,"https://www.pushplus.plus/send");sendCount++;
      const payload=JSON.parse(init.body);assert.equal(payload.to,"d".repeat(32));assert.equal(payload.channel,"wechat");
      return Response.json({code:200,data:"test-short-code"});
    };
    assert.equal((await runReminders(env)).queued,1);
    assert.equal((await runReminders(env)).queued,0);
    assert.equal(sendCount,1);
    let delivery=await DB.prepare("SELECT status FROM reminder_deliveries WHERE user_id=?1").bind(memberUser.id).first();
    assert.equal(delivery.status,"queued");
    await request(callbackPath,{method:"POST",body:{event:"message_complate",messageInfo:{shortCode:"test-short-code",sendStatus:2}}});
    delivery=await DB.prepare("SELECT status FROM reminder_deliveries WHERE user_id=?1").bind(memberUser.id).first();
    assert.equal(delivery.status,"sent");
    await DB.prepare("DELETE FROM reminder_deliveries").run();
    assert.equal((await finish(plain)).status,201);
    assert.equal((await finish(optional)).status,201);
    const later=minutes=>new Date(Date.now()+minutes*60_000);
    assert.equal((await runReminders(env,later(1))).queued,0);
    assert.equal(sendCount,1, "全部完成的成员不再提醒");
    await request(`/api/tasks/${optional.id}/checkin`,{cookie:member,method:"DELETE",body:{date}});
    await request("/api/notifications",{cookie:member,method:"PUT",body:{enabled:false}});
    assert.equal((await runReminders(env,later(2))).queued,0);
    assert.equal(sendCount,1, "关闭通知的成员不再提醒");
    await request("/api/notifications",{cookie:member,method:"PUT",body:{enabled:true}});
    globalThis.fetch=async(url,init)=>{
      if(String(url).endsWith("/getAccessKey")) return Response.json({code:200,data:{accessKey:"test-access",expiresIn:7200}});
      assert.match(String(url),/friend\/getQrCode/);
      assert.equal(init.headers["access-key"],"test-access");
      return Response.json({code:200,data:{qrCodeImgUrl:"https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=test"}});
    };
    assert.equal((await request("/api/notifications/qr",{cookie:member,method:"POST"})).status,200);
    assert.equal((await request("/api/notifications/qr",{cookie:member,method:"POST"})).status,429);
    globalThis.fetch=async()=>{
      await request(callbackPath,{method:"POST",body:{event:"message_complate",messageInfo:{shortCode:"early-code",sendStatus:2}}});
      return Response.json({code:200,data:"early-code"});
    };
    assert.equal((await runReminders(env,later(3))).queued,1);
    delivery=await DB.prepare("SELECT status FROM reminder_deliveries WHERE user_id=?1").bind(memberUser.id).first();
    assert.equal(delivery.status,"sent","提前到达的回调仍应记录成功");
    await DB.prepare("DELETE FROM reminder_deliveries").run();
    globalThis.fetch=async()=>Response.json({code:600},{status:429});
    assert.equal((await runReminders(env,later(4))).queued,0);
    delivery=await DB.prepare("SELECT status,error_code AS errorCode FROM reminder_deliveries WHERE user_id=?1").bind(memberUser.id).first();
    assert.equal(delivery.status,"failed");assert.equal(delivery.errorCode,"pushplus_600");
    assert.equal((await runReminders({...env,PUSHPLUS_TOKEN:""},later(5))).queued,0);
    const nextDate=new Date(Date.parse(date+"T00:00:00+08:00")+86_400_000);
    await runReminders({...env,PUSHPLUS_TOKEN:""},nextDate);
    const tomorrowPlan=await DB.prepare("SELECT due FROM task_days WHERE task_id=?1 AND local_date=?2").bind(plain.id,beijingDate(nextDate)).first();
    assert.equal(tomorrowPlan.due,0,"停用应在次日生效");
    assert.equal((await request("/api/notifications",{cookie:member,method:"DELETE"})).status,200);
    assert.equal((await (await request("/api/notifications",{cookie:member})).json()).bound,false);
    await request("/api/auth/logout",{cookie:member,method:"POST"});
    assert.equal((await request("/api/today",{cookie:member})).status,401);
  } finally {globalThis.fetch=originalFetch;await mf.dispose();}
});
